const carros = [
            "https://www.google.com/imgres?imgurl=http%3A%2F%2Fblog.intelbras.com.br%2Fwp-content%2Fuploads%2F2020%2F07%2Fcamera-com-reconhecimento-facial-mulher.png&tbnid=4I1iKyK_7FhNQM&vet=12ahUKEwju-uyZydD_AhVKuZUCHfe6CHcQMygHegUIARCnAQ..i&imgrefurl=https%3A%2F%2Fblog.intelbras.com.br%2Fcamera-com-reconhecimento-facial-conheca-essa-tecnologia%2F&docid=wTFD3F2i4XQ_OM&w=1200&h=628&q=camera%20de%20reconhecimento%20facial&ved=2ahUKEwju-uyZydD_AhVKuZUCHfe6CHcQMygHegUIARCnAQ"
            , "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.bitbest.com.br%2Fwp-content%2Fuploads%2F2020%2F02%2Fcamera-dome-reconhecimento-facial-lente-3-6-mm-5-mp-ir-40-mts-cmos-1-2-7-ip-67-ik10-mtidm045702-motorola-5413.png&tbnid=tLblTiPmSJ07gM&vet=12ahUKEwju-uyZydD_AhVKuZUCHfe6CHcQMygEegUIARChAQ..i&imgrefurl=https%3A%2F%2Fwww.bitbest.com.br%2Fproduto%2Fcamera-motorola-mtidm045702-moto-face-id-ip-2mp-para-reconhecimento-facial%2F&docid=392-vvs7EmWJPM&w=1200&h=675&q=camera%20de%20reconhecimento%20facial&ved=2ahUKEwju-uyZydD_AhVKuZUCHfe6CHcQMygEegUIARChAQ"
            ,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD5NicrgsYGOgyX7igFyrwzKgscA7O0r0kUQ&usqp=CAU"
            ,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT52IZTG24mVn9QLC2kUv1oFMvJBs_nfmzgIw&usqp=CAU"
            ,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKn0JxDKFU8iqujbZcxc9IWfaCB7GgR-7_28rpJ1i5YlD5F9ASq88LZ-Kz8CLrBG12bxo&usqp=CAU"       
]

const camera = document.getElementById("")